version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: chore
      include: scope
    groups:
      node-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /worker
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: chore
      include: scope
    ignore:
      - dependency-name: node
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: chore
      include: scope
