export const POPULAR_TECHNOLOGY_QUICK_STARTS = [
  "Next.js",
  "Next.js App Router",
  "React",
  "Vercel",
  "Tailwind CSS",
  "Cloudflare",
  "Stripe",
  "Shopify",
  "WordPress",
  "Sentry",
  "Google Analytics",
  "Google Tag Manager",
  "Google Workspace",
  "Node.js",
  "jQuery",
  "Bootstrap",
  "Webpack",
  "Radix UI",
  "shadcn/ui",
  "Framer Motion",
  "OpenAI",
  "Anthropic",
  "Lucide",
  "Turbopack",
  "PWA",
  "HTTP/3",
  "Open Graph",
  "Priority Hints",
  "HSTS",
  "Google Font API",
  "Nginx",
  "Amazon Web Services",
  "Amazon S3",
  "Amazon CloudFront",
  "Amazon Route 53",
  "Plausible",
  "Datadog",
  "Contentful",
  "Microsoft Clarity",
  "reCAPTCHA",
  "OneTrust",
  "Akamai",
  "Astro",
  "GSAP",
  "Docker",
  "PHP",
  "MySQL",
] as const;

export const POPULAR_TECHNOLOGY_COMBINATIONS = [
  ["Next.js", "Vercel"],
  ["Next.js", "React"],
  ["Next.js", "Node.js"],
  ["Next.js", "Next.js App Router"],
  ["React", "Tailwind CSS"],
  ["React", "Vercel"],
  ["React", "Webpack"],
  ["React", "Radix UI"],
  ["React", "Framer Motion"],
  ["Stripe", "Cloudflare"],
  ["Stripe", "React"],
  ["Shopify", "Google Analytics"],
  ["WordPress", "Google Analytics"],
  ["Sentry", "Next.js"],
  ["Sentry", "React"],
  ["Google Workspace", "Open Graph"],
  ["Google Workspace", "React"],
  ["Google Workspace", "Google Analytics"],
  ["Google Workspace", "Google Tag Manager"],
  ["Google Workspace", "OpenAI"],
  ["Cloudflare", "HTTP/3"],
  ["Cloudflare", "HSTS"],
  ["Cloudflare", "Open Graph"],
  ["Cloudflare", "Stripe"],
  ["Google Tag Manager", "Google Analytics"],
  ["Google Analytics", "React"],
  ["Node.js", "React"],
  ["Node.js", "Webpack"],
  ["Tailwind CSS", "Vercel"],
  ["Open Graph", "React"],
  ["Open Graph", "Stripe"],
  ["Open Graph", "PWA"],
  ["HSTS", "HTTP/3"],
  ["HSTS", "React"],
  ["Priority Hints", "React"],
  ["Framer Motion", "Open Graph"],
  ["Radix UI", "Next.js"],
  ["shadcn/ui", "Next.js"],
  ["Amazon Web Services", "Cloudflare"],
  ["Amazon S3", "Amazon CloudFront"],
] as const;
